---
# On the host where you are running ansible (could be linux/osx/whatever)
# first install the "openbsd_pkg" module, and make sure python version >= 2.5
#
- hosts: debian
  vars:
    get_recos: no
    target_help_dir: "/usr/share/doc/passwordsafe/help/"
  tasks:
  - name: Install requisites
    become: true
    become_method: sudo
    apt:
      name: "{{ item }}"
      state: present
      install_recommends: "{{ get_recos }}"
    with_items:
        - g++
        - git
        - uuid-dev
        - libuuid1
        - libgtest-dev
        - libuuid1
        - libwxgtk3.0-dev
        - libxerces-c-dev
        - libxt-dev
        - libxtst-dev
        - libykpers-1-dev
        - libyubikey-dev
        - make
        - zip
  - name: Clone repository
    git:
        repo: 'https://github.com/pwsafe/pwsafe.git'
        dest: pwsafe

  - name: Build pwsafe
    make:
        chdir: pwsafe
        target: "{{ item }}"
    with_items:
        - unicoderelease
        - help

  - name: Make pwsafe help dir
    become: true
    become_method: sudo
    file:
        path: "{{ target_help_dir }}"
        state: directory

# To do this in an idempotent manner, this requires remote globbing
# which I don't know how to do
  - name: Copy help files to pwsafe help dir
    become: true
    become_method: sudo
    shell: /bin/cp pwsafe/help/help*.zip "{{ target_help_dir }}"

...
