os:
    - osx

xcode_scheme:
    - pwsafe-release
    - pwsafe-debug

install:
    - brew install wxWidgets --with-static
    - Xcode/generate-configs-from-homebrew

script:
    - xcodebuild -project Xcode/pwsafe-xcode6.xcodeproj -scheme pwsafe
