# This is a basic workflow to help you get started with Actions

name: mac-pwsafe

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_mac_pwsafe:
    name: Build pwsafe for macOS
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Force compatible Xcode version
      run: sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
    
    - name: Print Xcode version in use
      run: xcode-select -p
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo "$GITHUB_WORKSPACE"

    - name: Set build parameters
      run: |
        echo "::set-env name=WX_VERS::3.1.4"
        echo "::set-env name=MACOS_VER_MIN::10.5"

    - name: Cache wxWidgets checkout
      id: cache-wxWidgets-checkout
      uses: actions/cache@v2
      with:
        path: ${{ env.home }}/wxWidgets
        key: wxWidgets-checkout

    - name: Cache wxWidgets build
      id: cache-wxWidgets-build
      uses: actions/cache@v2
      with:
        path: ${{ env.home }}/wxbuild
        key: ${{ env.WX_VERS }}-${{ env.MACOS_VER_MIN }}

    - name: Checkout wxWidgets
      if: steps.cache-wxWidgets-checkout.outputs.cache-hit != 'true'
      working-directory: ${{ env.HOME }}
      run: |
        git clone https://github.com/wxWidgets/wxWidgets.git

    - name: Build wxWidgets
      if: steps.cache-wxWidgets-build.outputs.cache-hit != 'true'
      working-directory: ${{ env.HOME }}/${{ env.WX_VERS }}
      run: |
        git pull origin
        git reset --hard v{{ env.WX_VERS }}
        rm -rf $HOME/wxbuild
        mkdir -p $HOME/wxbuild
        ./configure --prefix=$HOME/wxbuild --disable-shared --enable-unicode --with-macosx-version-min=$MACOS_VER_MIN
        make
        make install

    - name: Generate xcconfigs
      working-directory: ${{ github.workspace }}
      run: Xcode/generate-configs -r $HOME/wxbuild/bin/wx-config > Xcode/pwsafe-release.xcconfig
    
    - name: Build pwsafe
      working-directory: ${{ github.workspace }}
      run: xcodebuild -project Xcode/pwsafe-xcode6.xcodeproj -scheme pwsafe

    - name: Get Xcode build output location
      run: echo "::set-env name=BUILD_OUTPUT_DIR::$(xcodebuild -showBuildSettings -project Xcode/pwsafe-xcode6.xcodeproj | fgrep CONFIGURATION_BUILD_DIR | cut -d= -f2 | sed 's/^ *\(.*\)/\1/')"

    - name: Move app to another folder
      run: mkdir "$BUILD_OUTPUT_DIR"/app && mv "$BUILD_OUTPUT_DIR"/pwsafe.app "$BUILD_OUTPUT_DIR"/app/

    - name: Install dependencies for creating dmg
      run: brew install create-dmg

    - name: Create dmg
      run: create-dmg --volname "Password Safe" --volicon "src/ui/wxWidgets/graphics/pwsafe.icns" --eula LICENSE ${{ github.workspace }}/PasswordSafe.dmg "$BUILD_OUTPUT_DIR/app"

    - name: Upload artifacts
      uses: 'actions/upload-artifact@v2'
      with:
        name: PasswordSafe.${{ github.sha }}.dmg
        path: ${{ github.workspace }}/PasswordSafe.dmg
